name: Cache checking with internal pr branch
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
env:
  GO_VERSION: '1.22'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
    - name: Setup tar default options
      shell: bash
      run: echo "TAR_OPTIONS=--skip-old-files" >> $GITHUB_ENV

    - name: building defsec
      run: echo "Building defsec..."

    - uses: actions/checkout@v5


    - uses: lmvysakh/setup-go@windows_runner_cache_load_fix
      with:
        go-version: ${{ env.GO_VERSION }}
   
    - name: Display Go version
      run: go version
   