name: Huge Go Module Cache Test with setup-go (Preserve Root Files, Go 1.24) - v5

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  big-cache-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Go with cache
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: bigcachetest/go.sum

      - name: Clean Go module cache
        run: go clean -modcache

      - name: Create large go.mod in test directory
        working-directory: bigcachetest
        run: |
          cat <<EOF > go.mod
          module example.com/bigcachetest

          go 1.24

          require (
                github.com/aws/aws-sdk-go-v2 v1.29.0
                cloud.google.com/go v0.110.0
                github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.1.0
                github.com/lib/pq v1.10.9
                github.com/go-sql-driver/mysql v1.7.0
                github.com/golang/protobuf v1.5.3
                github.com/elastic/go-elasticsearch/v8 v8.10.0
                go.uber.org/zap v1.24.0
                github.com/prometheus/client_golang v1.16.0
                github.com/gin-gonic/gin v1.9.0
                github.com/go-redis/redis/v8 v8.11.5
                github.com/gorilla/websocket v1.5.0
                github.com/sirupsen/logrus v1.9.3
                github.com/spf13/cobra v1.8.0
                github.com/spf13/viper v1.18.2
                go.mongodb.org/mongo-driver v1.13.1
                github.com/google/uuid v1.6.0
                github.com/minio/minio-go/v7 v7.0.28
                k8s.io/client-go v0.29.0
                github.com/apache/thrift v0.19.0
                github.com/apache/arrow/go/v13 v13.0.0
                github.com/nats-io/nats.go v1.22.1
                github.com/segmentio/kafka-go v0.4.30
                github.com/googleapis/gax-go/v2 v2.7.0
                github.com/gocql/gocql v1.5.0
            )
          EOF

      - name: Create dummy Go file to force dependency download
        working-directory: bigcachetest
        run: |
          cat <<EOF > dummy.go
          package main

          import (
              _ "github.com/aws/aws-sdk-go-v2/aws"
              _ "cloud.google.com/go"
              _ "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
              _ "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute"
              _ "github.com/lib/pq"
              _ "github.com/go-sql-driver/mysql"
              _ "github.com/golang/protobuf/proto"
              _ "github.com/elastic/go-elasticsearch/v8"
              _ "go.uber.org/zap"
              _ "github.com/prometheus/client_golang/prometheus"
              _ "github.com/gin-gonic/gin"
              _ "github.com/go-redis/redis/v8"
              _ "github.com/gorilla/websocket"
              _ "github.com/sirupsen/logrus"
              _ "github.com/spf13/cobra"
              _ "github.com/spf13/viper"
              _ "go.mongodb.org/mongo-driver/mongo"
              _ "github.com/google/uuid"
              _ "github.com/minio/minio-go/v7"
              _ "k8s.io/client-go/kubernetes"
              _ "github.com/apache/thrift/lib/go/thrift"
              _ "github.com/apache/arrow/go/arrow"
              _ "github.com/nats-io/nats.go"
              _ "github.com/segmentio/kafka-go"
              _ "github.com/googleapis/gax-go/v2"
              _ "github.com/gocql/gocql"
          )
          func main() {}
          EOF

      - name: Tidy go.mod and go.sum
        working-directory: bigcachetest
        run: go mod tidy

      - name: Download dependencies
        working-directory: bigcachetest
        run: go mod download

      - name: Check Go module cache size
        run: du -sh ~/go/pkg/mod

  big-cache-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Go with cache
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: bigcachetest/go.sum

      - name: Clean Go module cache
        run: go clean -modcache

      - name: Create large go.mod in test directory
        working-directory: bigcachetest
        run: |
          cat <<EOF > go.mod
          module example.com/bigcachetest

          go 1.24

          require (
              github.com/aws/aws-sdk-go-v2 v1.29.0
              cloud.google.com/go v0.110.0
              github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.1.0
              github.com/lib/pq v1.10.9
              github.com/go-sql-driver/mysql v1.7.0
              github.com/golang/protobuf v1.5.3
              github.com/elastic/go-elasticsearch/v8 v8.10.0
              go.uber.org/zap v1.24.0
              github.com/prometheus/client_golang v1.16.0
              github.com/gin-gonic/gin v1.9.0
              github.com/go-redis/redis/v8 v8.11.5
              github.com/gorilla/websocket v1.5.0
              github.com/sirupsen/logrus v1.9.3
              github.com/spf13/cobra v1.8.0
              github.com/spf13/viper v1.18.2
              go.mongodb.org/mongo-driver v1.13.1
              github.com/google/uuid v1.6.0
              github.com/minio/minio-go/v7 v7.0.28
              k8s.io/client-go v0.29.0
              github.com/apache/thrift v0.19.0
              github.com/apache/arrow/go/v13 v13.0.0
              github.com/nats-io/nats.go v1.22.1
              github.com/segmentio/kafka-go v0.4.30
              github.com/googleapis/gax-go/v2 v2.7.0
              github.com/gocql/gocql v1.5.0
          )

          EOF

      - name: Create dummy Go file to force dependency download
        working-directory: bigcachetest
        run: |
          cat <<EOF > dummy.go
          package main

          import (
              _ "github.com/aws/aws-sdk-go-v2/aws"
              _ "cloud.google.com/go"
              _ "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
              _ "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute"
              _ "github.com/lib/pq"
              _ "github.com/go-sql-driver/mysql"
              _ "github.com/golang/protobuf/proto"
              _ "github.com/elastic/go-elasticsearch/v8"
              _ "go.uber.org/zap"
              _ "github.com/prometheus/client_golang/prometheus"
              _ "github.com/gin-gonic/gin"
              _ "github.com/go-redis/redis/v8"
              _ "github.com/gorilla/websocket"
              _ "github.com/sirupsen/logrus"
              _ "github.com/spf13/cobra"
              _ "github.com/spf13/viper"
              _ "go.mongodb.org/mongo-driver/mongo"
              _ "github.com/google/uuid"
              _ "github.com/minio/minio-go/v7"
              _ "k8s.io/client-go/kubernetes"
              _ "github.com/apache/thrift/lib/go/thrift"
              _ "github.com/apache/arrow/go/arrow"
              _ "github.com/nats-io/nats.go"
              _ "github.com/segmentio/kafka-go"
              _ "github.com/googleapis/gax-go/v2"
              _ "github.com/gocql/gocql"
          )
          func main() {}
          EOF

      - name: Tidy go.mod and go.sum
        working-directory: bigcachetest
        run: go mod tidy

      - name: Download dependencies
        working-directory: bigcachetest
        run: go mod download

      - name: Check Go module cache size
        run: du -sh ~/go/pkg/mod

  big-cache-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Go with cache
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: bigcachetest/go.sum

      - name: Clean Go module cache
        run: go clean -modcache

      - name: Create large go.mod in test directory
        working-directory: bigcachetest
        run: |
          $goMod = @"
          module example.com/bigcachetest

          go 1.24

          require (
              github.com/aws/aws-sdk-go-v2 v1.29.0
              cloud.google.com/go v0.110.0
              github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.1.0
              github.com/lib/pq v1.10.9
              github.com/go-sql-driver/mysql v1.7.0
              github.com/golang/protobuf v1.5.3
              github.com/elastic/go-elasticsearch/v8 v8.10.0
              go.uber.org/zap v1.24.0
              github.com/prometheus/client_golang v1.16.0
              github.com/gin-gonic/gin v1.9.0
              github.com/go-redis/redis/v8 v8.11.5
              github.com/gorilla/websocket v1.5.0
              github.com/sirupsen/logrus v1.9.3
              github.com/spf13/cobra v1.8.0
              github.com/spf13/viper v1.18.2
              go.mongodb.org/mongo-driver v1.13.1
              github.com/google/uuid v1.6.0
              github.com/minio/minio-go/v7 v7.0.28
              k8s.io/client-go v0.29.0
              github.com/apache/thrift v0.19.0
              github.com/apache/arrow/go/v13 v13.0.0
              github.com/nats-io/nats.go v1.22.1
              github.com/segmentio/kafka-go v0.4.30
              github.com/googleapis/gax-go/v2 v2.7.0
              github.com/gocql/gocql v1.5.0
          )

          "@
          Set-Content -Path go.mod -Value $goMod

      - name: Create dummy Go file to force dependency download
        working-directory: bigcachetest
        run: |
          $dummyGo = @"
          package main

          import (
                _ "github.com/aws/aws-sdk-go-v2/aws"
                _ "cloud.google.com/go"
                _ "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"
                _ "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute"
                _ "github.com/lib/pq"
                _ "github.com/go-sql-driver/mysql"
                _ "github.com/golang/protobuf/proto"
                _ "github.com/elastic/go-elasticsearch/v8"
                _ "go.uber.org/zap"
                _ "github.com/prometheus/client_golang/prometheus"
                _ "github.com/gin-gonic/gin"
                _ "github.com/go-redis/redis/v8"
                _ "github.com/gorilla/websocket"
                _ "github.com/sirupsen/logrus"
                _ "github.com/spf13/cobra"
                _ "github.com/spf13/viper"
                _ "go.mongodb.org/mongo-driver/mongo"
                _ "github.com/google/uuid"
                _ "github.com/minio/minio-go/v7"
                _ "k8s.io/client-go/kubernetes"
                _ "github.com/apache/thrift/lib/go/thrift"
                _ "github.com/apache/arrow/go/arrow"
                _ "github.com/nats-io/nats.go"
                _ "github.com/segmentio/kafka-go"
                _ "github.com/googleapis/gax-go/v2"
                _ "github.com/gocql/gocql"
            )
          func main() {}
          "@
          Set-Content -Path dummy.go -Value $dummyGo

      - name: Tidy go.mod and go.sum
        working-directory: bigcachetest
        run: go mod tidy

      - name: Download dependencies
        working-directory: bigcachetest
        run: go mod download

      - name: Check Go module cache size
        run: du -sh $env:USERPROFILE\go\pkg\mod

